#pragma once

#include <chrono>
#include <cstddef>
#include <cstdint>
#include <map>
#include <shared_mutex>
#include <string>
#include <vector>

#include <opencv2/core.hpp>

struct ArucoMappingStatus
{
    bool configured = false;
    bool homographyValid = false;
    bool homographyFresh = false;
    bool staticHomography = false;
    int detectedMarkers = 0;
    int acceptedMarkers = 0;
    int inlierCorners = 0;
    double reprojectionRmsPx = 0.0;
    double homographyAgeMs = 0.0;
    bool lensCalibrationConfigured = false;
    bool lensCalibrationApplied = false;
    double lensCalibrationRmsPx = 0.0;
    std::string message;
};

// Dynamic ground-plane mapper. Known ArUco marker geometry replaces the old
// user-clicked image ROI calibration points. Every accepted camera frame may
// refresh image -> factory-world Homography, so small camera movement is
// corrected while enough board markers remain visible.
class GridCoordinateMapper
{
public:
    static constexpr int GRID_SIZE = 60;
    static constexpr int USABLE_MIN = 0;
    static constexpr int USABLE_MAX = GRID_SIZE - 1;

    bool loadArucoBoardConfiguration(
        const std::string& configurationPath,
        std::size_t channelIndex);

    // Optional per-lens intrinsic calibration. The YAML is generated by the
    // ChArUco calibrator. Marker corners and fire-base points are corrected in
    // point space, avoiding a full-frame remap on Raspberry Pi.
    bool loadCameraCalibration(
        const std::string& calibrationPath,
        std::size_t channelIndex);

    // Installation mode persists the accepted normalized-image -> factory
    // Homography. Production can then run without visible floor markers.
    bool saveStaticHomography(const std::string& homographyPath);
    bool loadStaticHomography(
        const std::string& homographyPath,
        std::size_t channelIndex);
    bool hasStaticHomography() const;

    // Returns true only when this frame produced and accepted a new Homography.
    bool updateFromFrame(const cv::Mat& frame, std::uint64_t frameId);

    // Input is normalized image position [0,1]. Output uses zero-based
    // coordinates for the complete 60x60 display: x/y are both 0..59.
    bool map(
        const cv::Point2f& normalizedImagePoint,
        cv::Point& gridPoint,
        cv::Point2f* factoryWorldPointM = nullptr) const;

    void resetTracking();
    bool isConfigured() const;
    bool isReady() const;
    ArucoMappingStatus status() const;
    std::string lastError() const;
    std::string cameraCalibrationError() const;

private:
    using Clock = std::chrono::steady_clock;

    struct MarkerDefinition
    {
        int id = -1;
        cv::Point2f centerWorldM;
        float sizeM = 0.0F;
        float clockwiseRotationDegrees = 0.0F;
    };

    std::vector<cv::Point2f> markerWorldCorners(
        const MarkerDefinition& marker,
        float modelScale) const;
    bool homographyIsFreshLocked(Clock::time_point now) const;
    std::string configurationSignatureLocked() const;
    std::string lensCalibrationSignatureLocked() const;

    mutable std::shared_mutex mutex_;
    int dictionaryId_ = -1;
    std::map<int, MarkerDefinition> markers_;
    cv::Rect2f boardWorldM_;
    cv::Rect2f factoryWorldM_;
    float modelScale_ = 1.0F;
    cv::Mat homographyImageToWorld_;
    std::vector<cv::Point2f> boardImagePolygon_;
    cv::Mat cameraMatrix_;
    cv::Mat distortionCoefficients_;
    cv::Size calibrationImageSize_;
    cv::Size homographyFrameSize_;
    bool lensCalibrationConfigured_ = false;
    bool staticHomographyLoaded_ = false;
    double lensCalibrationRmsPx_ = 0.0;
    std::string cameraCalibrationError_;

    bool configured_ = false;
    std::size_t channelIndex_ = 0;
    int minimumVisibleMarkers_ = 2;
    int minimumInlierCorners_ = 8;
    double maximumReprojectionRmsPx_ = 5.0;
    int maximumHoldMs_ = 1500;
    std::uint64_t updateEveryFrames_ = 1;
    double smoothingAlpha_ = 0.45;
    std::uint64_t lastAttemptFrameId_ = 0;
    bool hasAttemptedFrame_ = false;
    Clock::time_point lastGoodUpdate_{};
    ArucoMappingStatus status_;
    std::string lastError_;
};
